post_analyzer_bot_username:
  description: "The username of the AI bot you want to use for analyzing posts in chat."
  type: string
  default: ""
analyze_post_icon:
  description: "The used icon on posts"
  type: string
  default: "discourse-sparkles"
svg_icons:
  default: ""
  type: list
  list_type: "compact"
  description: "List of FontAwesome 6 icons used in this theme component"
